/*
 * Do not edit by hand.
 * Automatically generated by fistgen.
 */
#ifndef _fist_kdb3fs_h
#define _fist_kdb3fs_h

/* OPTIONAL DECLARATIONS FOLLOW */


/*
 * kdb3fs: modifies file names and file data (same as base3fs)
 */

/* MACROS AND STRUCTURES BASED ON FIST FILE tests/kdb3fs.fist */

/* Name of the file system? */
#define FIST_FSNAME "kdb3fs"

/* What access mode: readonly, writeonly, or readwrite? */
/* #undef FIST_ACCESSMODE_READONLY */
/* #undef FIST_ACCESSMODE_WRITEONLY */
#define FIST_ACCESSMODE_READWRITE 1

/* Turn on debugging? */
#define FIST_DEBUG 1

/* Turn on dynamic_inode_numbers? */
/* #undef FIST_DYNAMIC_INODE_NUMBERS */

/* Manipulate file data? */
#define FIST_FILTER_DATA 1

/* Manipulate file names? */
#define FIST_FILTER_NAME 1

/* Size changing algorithm filter? */
/* #undef FIST_FILTER_SCA */

/* What mount style: regular, overlay, or attach? */
#define FIST_MNTSTYLE_REGULAR 1
/* #undef FIST_MNTSTYLE_OVERLAY */
/* #undef FIST_MNTSTYLE_ATTACH */

/* fan-out value */
#define FIST_FANOUT 1

/* What encoding type: none, stream, or block? */
#define FIST_ENCODING_TYPE_NONE 1
/* #undef FIST_ENCODING_TYPE_STREAM */
/* #undef FIST_ENCODING_TYPE_BLOCK */

/* encoding-blocksize VALUE */
#define FIST_ENCODING_BLOCKSIZE 1

/* Error codes? */
/* no error codes defined */

/* Mount flags? */
/* no error codes defined */

/* Mount data arguments? */
/* no mount data defined */

/* Per-VFS data? */
/* no per-VFS data defined */

/* Per-vnode data? */
/* no per-vnode data defined */

/* file formats */
/* using auxiliary sources? */
/* #undef FIST_USE_AUX_SRC */
/* no fileformats defined */

#endif /* not _fist_kdb3fs_h */
